#!/bin/sh

# env
BROWSER_CMD="x-www-browser"
CAPTURE_CMD="import"
FLICKR_CMD="flickcurl"
TMPFILE="/tmp/fyazo_upload$$.png"
TITLE="fyazo`date +%Y%m%d%H%M%S`"
TAG="fyazo"

# function
command_installed () {
    if which $1 >/dev/null 2>&1; then :; else
	echo "*** not found \"$1\" command."
	exit 1
    fi
}

# command check
command_installed $BROWSER_CMD
command_installed $CAPTURE_CMD
command_installed $FLICKR_CMD
if $FLICKR_CMD test.login > /dev/null 2>&1; then :; else
    echo "*** should setup \".flickcurl.conf\"."
    exit 1
fi

# capture
sleep 3
$CAPTURE_CMD $TMPFILE
if test -f $TMPFILE; then :; else
    echo "*** can't capture with \"$CAPTURE_CMD\" command."
    exit 2
fi

# upload
PHOTOID=`$FLICKR_CMD upload $TMPFILE title $TITLE tags $TAG 2>&1 | tail -n 1 | sed -e "s/^.*Photo ID: \(.*$\)$/\1/"`
echo Photo ID: $PHOTOID

# cleanup
rm -f $TMPFILE

# open with web browser
if test -z "$PHOTOID"; then
    echo "*** $FLICKR_CMD upload error."
    exit 3
fi

SHORTURI=`$FLICKR_CMD shorturi $PHOTOID 2>&1 | sed -e "s/^.*\(http.*$\)$/\1/"`
echo URL: $SHORTURI

if test -z "$SHORTURI"; then
    echo "*** $FLICKR_CMD get shorturi error."
    exit 4
fi
$BROWSER_CMD $SHORTURI
